kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rollout-notifier
rules:
- apiGroups: ["app"]
  resources: ["deployments"]
  verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rollout-notifier
subjects:
- kind: ServiceAccount
  name: rollout-notifier
  namespace: rollout-notifier
roleRef:
  kind: ClusterRole
  name: rollout-notifier
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollout-notifier
